version: "3"
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    networks:
      - backend
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: interview123

  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: interview123
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db-vol:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    container_name: backend_api
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      - db

  frontend:
    container_name: next_frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  backend:

volumes:
  db-vol:
